
# Classes
module Stone
  class StoneError < RuntimeError
    def initialize: (String msg) -> void
                  | (String msg, untyped ast) -> void
  end

  class ParseError < StandardError
    def location: (Token token) -> String
    def initialize: ((String | Token) obj) -> void
                  | (String obj, Token? token) -> void
  end
end
